services:
  - type: web
    name: contact-manager-api
    env: node
    root: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
